#web:
#  image: t.b.d.
#  container_name: webapp-container

configuration-server:
  image: springcloud/configserver
  container_name: config-server
  ports:
   - "8888:8888"
  environment:
    EUREKA_SERVICE_URL: service-registry-1
  external_links:
   - service-registry-1

#
#  ports:
#   - "5000:5000"
#  volumes:
#   - .:/code
#  links:
#   - redis
#
#customer-service:
#  image: customer-service
#  container_name: customer-service-1
#
#account-service:
#  image: account-service
#  container_name: account-service-1

#database:
#  image: mongo